### ISSUE TITLE
Running Error

### ISSUE THREAD

**Issue by wangyang-stu** [jquesnelle/yarn#44]
When launching finetune. py using the following command:
CUDA_VISIBLE_DEVICES=0,1,2,3,4 accelerate launch finetune.py  --output-dir output/yarn-7b-64k --model /data/wy/llm_base/Llama-2-7b-hf --dataset /data/wy/LLMScaledData/pg_books-tokenized-bos-eos-chunked-6/data

The following error occurred:
Traceback (most recent call last):
  File "/data/wy/yarn/finetune.py", line 293, in <module>
    main(args.parse_args())
  File "/data/wy/yarn/finetune.py", line 156, in main
    model.gradient_checkpointing_enable()
  File "/home/centos/anaconda3/envs/llm_sacled/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1614, in __getattr__
    raise AttributeError("'{}' object has no attribute '{}'".format(
AttributeError: 'DistributedDataParallel' object has no attribute 'gradient_checkpointing_enable'

Need to modify 'model.gradient_checkpointing_enable()' to 'model.module.gradient_checkpointing_enable()'

**Comment by ichsan2895** [comment]
I got same problem. Did modify `model.gradient_checkpointing_enable()` to `model.module.gradient_checkpointing_enable()` solve the problem?

**Comment by 18140663659** [comment]
> model.module.gradient_checkpointing_enable()

same question
